[build-system]
requires = ["setuptools", "wheel"]

[tool.poetry]
name = "gull-api"
version = "0.1.0"
description = "A REST API for running Large Language Models"
authors = ["Michael Becker <michael.becker@uphs.upenn.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.68.0"
uvicorn = "^0.15.0"
httpx = "^0.19.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
