name: Docker Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Extract release version
      id: release-version
      run: echo "::set-output name=version::${{ github.event.release.tag_name }}"

    - name: Update version in pyproject.toml
      run: sed -i "s/version = \".*\"/version = \"${{ steps.release-version.outputs.version }}\"/" pyproject.toml

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/gull-api

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
