name: PyPI Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  test:
    uses: ./.github/workflows/run_test.yml@main
    
  pypi-publish:
    needs: [test]
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Extract release version
      id: release-version
      run: echo "::set-output name=version::${{ github.event.release.tag_name }}"
      
    - name: Update and validate version in pyproject.toml
      run: |
        # Replacing the placeholder version with the actual version from the tag
        sed -i "s/version = \"0.0.0\"/version = \"${{ steps.release-version.outputs.version }}\"/" pyproject.toml
        # Validate that the version follows semantic versioning
        if ! echo "${{ steps.release-version.outputs.version }}" | grep -Pq '^\d+(\.\d+){2}'; then
          echo "Invalid version format. Should be semantic versioning."
          exit 1
        fi
      
    - name: Install Poetry
      uses: snok/install-poetry@v1.2
      
    - name: Build Python package
      run: poetry build
      
    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish --username=__token__ --password=$PYPI_TOKEN

    - name: Validate package on PyPI
      run: |
        PACKAGE_NAME="gull-api"
        PACKAGE_VERSION="${{ steps.release-version.outputs.version }}"
        curl --head --fail "https://pypi.org/project/${PACKAGE_NAME}/${PACKAGE_VERSION}/"
